apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: briddockchristopher@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          project: identity-415323
          serviceAccountSecretRef:
            name: clouddns-svc-acct
            key: identity-415323-7d62616fe5ba.json
