trigger:
- main

pool:
  name: Default

variables:
- group: Service.Identity

stages:
- stage: 'Build'
  displayName: 'Build Service'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    - task: Bash@3
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/tokenizer.sh'
        arguments: '--db-host $(dbHost) --db-port $(dbPort) --db-username $(dbUsername) --db-password "$(dbPassword)" --db-name $(dbName) --jwt-issuer $(jwtIssuer) --jwt-audience $(jwtAudience) --jwt-secret $(jwtSecret) --jwt-expires $(jwtExpires) --rabbit-host $(rabbitHostname) --rabbit-username $(rabbitUsername) --rabbit-password $(rabbitPassword) --enable-feature "RabbitMq"'
        workingDirectory: 'src/ChristopherBriddock.Service.Identity/'
    - script: |
        dotnet build --configuration Release src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj
      displayName: 'Build & Restore'
    - script: |
        dotnet test --collect:"XPlat Code Coverage" src/ChristopherBriddock.Service.Identity.Tests/ChristopherBriddock.Service.Identity.Tests.csproj
      displayName: 'Test'
    - script: |
        dotnet publish src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj -c Release
      displayName: 'Publish'
    - script: dotnet tool update --global dotnet-reportgenerator-globaltool
      continueOnError: true
      enabled: true
      displayName: 'Install Code Coverage Tool'
    - script: |
        cd src/ChristopherBriddock.Service.Identity.Tests/TestResults
        reportgenerator -reports:"*/coverage.cobertura.xml" -targetdir:"../coveragereport" -reporttypes:Html
      displayName: 'Code Coverage Report'
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: 'src/ChristopherBriddock.Service.Identity.Tests/TestResults/*/coverage.cobertura.xml'
        pathToSources: 'src/ChristopherBriddock.Service.Identity/'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/workerservice-email-k8s.dev.yaml
          **/service-identity-k8s.dev.yaml
          **/src/ChristopherBriddock.Service.Identity/bin/Release/net8.0/publish/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
        flattenFolders: true     
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
