trigger:
- main
- dev

pool:
  name: Default

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - script: |
      dotnet build --configuration Release src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj
    displayName: 'Build & Restore'
  - script: |
      dotnet test --collect:"XPlat Code Coverage" src/ChristopherBriddock.Service.Identity.Tests/ChristopherBriddock.Service.Identity.Tests.csproj
    displayName: 'Test'
  - script: |
      dotnet publish src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj -c Release
    displayName: 'Publish'
