apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      automountServiceAccountToken: false
      containers:
      - name: postgres
        image: postgres:latest
        resources:
          requests:
            memory: "4096Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "12288Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
        envFrom:
        - secretRef:
            name: postgres-secrets
        volumeMounts:
        - mountPath: /var/lib/postgresql/storage
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pvc