apiVersion: v1
kind: Service
metadata:
  name: service-identity-lb
spec:
  type: LoadBalancer
  selector:
    app: service-identity
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
