version: '3.4'

services:
  
  # christopherbriddock.service.identity:
  #   image: ${DOCKER_REGISTRY-}christopherbriddockserviceidentity
  #   build:
  #     context: .
  #     dockerfile: ChristopherBriddock.Service.Identity/Dockerfile

  # christopherbriddock.service.email:
  #   image: ${DOCKER_REGISTRY-}christopherbriddockserviceemail
  #   build:
  #     context: .
  #     dockerfile: ChristopherBriddock.Service.Email/Dockerfile
  
  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QIuBoN9hFritmO5JCL1ElTGUodPFUF4OIn2wM7nQV77x9HxoxCRFK8/lzhRJe+synMKXluA9JsBx5ffKOrDVXoUSCBF4NVqZ4nT89VaBJQP6
    ports:
      - "80:80"
      - "443:443"
      - "5341:5341"
      - "45341:45341"
    volumes:
      - ./seq:/data

  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:3.12.12-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

