name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install Dependencies
      run: sudo apt-get install jq
    - name: Generate JWT Token
      run: |
        export PATH="$PATH:~/.dotnet/tools"
        JWT=$(dotnet user-jwts create --output json | jq -r .token)
        echo "JWT=$JWT" >> $GITHUB_ENV
    - name: Build & Restore
      run: dotnet build --configuration Release src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=minimal" src/ChristopherBriddock.Service.Identity.Tests/ChristopherBriddock.Service.Identity.Tests.csproj
      env:
        JWT: ${{ env.JWT }}
    - name: Publish
      run: dotnet publish src/ChristopherBriddock.Service.Identity/ChristopherBriddock.Service.Identity.csproj -c Release